= The casl CLI

A proposal for a new CLI to help us manage cloud provisioning jobs

== Problem Statement

Major work has been done in CASL to automate full provisioning of environments for OpenShift and other peripheral services in public and private Clouds using ansible. As we continue to add features, support for new cloud providers, and scale out the user base for these tools it's becoming increasingly important to have better client tooling for running these provisioning jobs.

The first step we've taken to assist with this is to containerize all of the client tools that are needed to run these jobs and deliver them via docker images. Now, rather than having to install and manage a bunch of packages locally to get started (i.e. for openstack):

----
yum install -y https://repos.fedorapeople.org/repos/openstack/openstack-liberty/rdo-release-liberty-3.noarch.rpm; \
yum update -y; \
yum install -y python-devel epel-release; \
yum install -y git tar bind-utils ansible1.9 python-pip python-ceilometerclient python-cinderclient python-glanceclient \
 python-heatclient python-neutronclient python-novaclient python-saharaclient python-swiftclient python-troveclient python-openstackclient python-passlib; \
yum clean all
----

We just have you run a docker container (managed by a run script) that already contains all this stuff, like:

----
./docker/openstack-docker-client/run.sh --repository=/path/to/ansible/git/repository
----

This is much easier to set up. However, as we start to scale out to different clouds, or run various different provisining profiles, we're still having to do a lot of management of things like SSH Keys, credentials, inventory files, etc. We end up wasting a lot of time between running jobs just trying to track down all of the dependencies for each run.

This is approximately what I do to provision two different environments against two different clouds

----
./docker/openstack-docker-client/run.sh --repository=/path/to/ansible/git/repository
bash~# cd repository/rhc-ose/rhc-ose-ansible/
bash~# cp ~/.openstack/openrc.sh.cloud1 ~/.openstack/openrc.sh
bash~# cp ~/.ssh/my_key.cloud1 ~/.ssh/id_rsa.pub
bash~# cp /path/to/inventory_for_dev .
bash~# provision.sh --inventory=inventory_for_dev --path-to-code=/root/repository/rhc-ose/rhc-ose-ansible

.... run succeeds! ...
bash~# exit

# And start all over again
./docker/aws-docker-client/run.sh --repository=/path/to/ansible/git/repository
bash~# cd repository/rhc-ose/rhc-ose-ansible/
bash~# cp ~/.aws/creds ~/.openstack/openrc.sh
bash~# cp ~/.ssh/my_key.aws ~/.ssh/id_rsa.pub
bash~# cp /path/to/inventory_for_prod .
bash~# provision.sh --inventory=inventory_for_prod --path-to-code=/root/repository/rhc-ose/rhc-ose-ansible
----

There's a lot of overhead here if i'm a first time user, or if i want to run this multiple times to test changes to any of my code.

== Proposed CLI

We should create a (vagrant style) one-time-setup style CLI tool where we can define our local environment once, sorted into profiles for a certain environment/cloud combination and then have a simple command to kick off provisioning jobs. A local config might look like:

----
# cat .caslcfg
[dev_cloud1]
client_image=./docker/openstack-docker-client
public_key=~/.ssh/id_rsa_cloud1
cloud_creds=~/.openstack/openrc.sh.cloud1
inventory=~/path/to/inventory_for_dev

[prod_cloud2]
client_image=./docker/openstack-docker-client
public_key=~/.ssh/id_rsa_cloud2
cloud_creds=~/.openstack/openrc.sh.cloud2
inventory=~/path/to/inventory_for_prod

[prod_aws]
client_image=./docker/aws-docker-client
public_key=~/.ssh/id_rsa_cloud2
cloud_creds=~/.aws/creds
inventory=~/path/to/inventory_for_prod
----

From there we can create a simple CLI that allows to run single, short commands against the profiles defined above.

----
casl dev_cloud1 up/down
casl prod_cloud2 up/down
casl prod_aws up/down
----
