---
# Provision OpenStack instances
- hosts: localhost
  pre_tasks:
  - include: roles/openstack-create/pre_tasks/pre_tasks.yml
  - include: roles/common/pre_tasks/pre_tasks.yml
  - include: roles/subscription-manager/pre_tasks/pre_tasks.yml
  roles:
    - role: common
    - role: openshift-common
    # Provision Master
    - role: openstack-create
      type: "master"
      image_name: "{{ openshift_openstack_image_name }}"
      security_groups: "{{ openshift_openstack_master_security_groups }}"
      key_name: "{{ openstack_key_name }}"
      flavor_name: "{{ openshift_openstack_flavor_name }}"
      register_host_group: "openshift_masters"
      node_count: "{{ openshift_master_count }}"
      disk_volume: "{{ openshift_storage_disk_volume }}"
      volume_size: "{{ openshift_openstack_master_storage_size }}"
    # Provision Nodes
    - role: openstack-create
      type: "node"
      image_name: "{{ openshift_openstack_image_name }}"
      security_groups: "{{ openshift_openstack_node_security_groups }}"
      key_name: "{{ openstack_key_name }}"
      flavor_name: "{{ openshift_openstack_flavor_name }}"
      register_host_group: "openshift_nodes"
      node_count: "{{ openshift_node_count }}"
      disk_volume: "{{ openshift_storage_disk_volume }}"
      volume_size: "{{ openshift_openstack_master_storage_size }}"

    # Provision DNS

- include: playbooks/dns-provision.yaml

- hosts: all:!dns:!localhost
  remote_user: "cloud-user"
  become: true
  become_user: root
  vars:
    ansible_ssh_user: cloud-user
    ansible_user: cloud-user
  roles:
    - role: hostnames

- hosts: all:!localhost
  remote_user: "cloud-user"
  become: true
  vars:
    ansible_ssh_user: cloud-user
    ansible_user: cloud-user
  roles:
    - { role: subscription-manager, repos: ["rhel-7-server-rpms", "rhel-7-server-ose-3.1-rpms", "rhel-7-server-extras-rpms"] }

- hosts: dns
  remote_user: "cloud-user"
  become: true
  vars:
    ansible_ssh_user: cloud-user
    ansible_user: cloud-user
  pre_tasks:
  - name: "Generate dns-server views"
    include: playbooks/dns_dual_view.yaml
    delegate_to: localhost
  - name: "Include the generated views"
    include_vars: /tmp/named_views.yaml
    delegate_to: localhost
  - name: "Include generated dns records"
    include_vars: /tmp/records.yaml
    delegate_to: localhost
  roles:
    - role: dns-server
    - role: dns

# Install and configure OpenShift

- hosts: openshift-masters:openshift-nodes
  become: true
  become_method: sudo
  vars:
    ansible_ssh_user: cloud-user
    ansible_user: cloud-user
  tasks:
  - name: "Edit /etc/resolv.conf on masters/nodes"
    lineinfile:
      state: present
      dest: /etc/resolv.conf
      regexp: "nameserver {%for host in groups['dns']%} {{ hostvars[host].dns_public_ip }} {% endfor %}"
      line: "nameserver {%for host in groups['dns']%} {{ hostvars[host].dns_public_ip }} {% endfor %}"
      insertafter: search*
  roles:
    - { role: docker, tags: 'docker' }
    - { role: openshift-provision, tags: 'openshift-provision', ansible_sudo: true }

- hosts: localhost
  roles:
    - openshift-install
  post_tasks:
    - name: "Edit /etc/hosts in container"
      lineinfile:
        state: present
        dest: /etc/hosts
        regexp: "{%for host in groups['openshift_masters']%}{{ hostvars[host].dns_public_ip }} {{ hostvars[host].ansible_hostname }}{{dns_domain}}\n{% endfor %}"
        line:   "{%for host in groups['openshift_masters']%}{{ hostvars[host].dns_public_ip }} {{ hostvars[host].ansible_hostname }}{{dns_domain}}\n{% endfor %}"
    - name: "Edit /etc/hosts in container"
      lineinfile:
        state: present
        dest: /etc/hosts
        regexp: "{%for host in groups['openshift_nodes']%}{{ hostvars[host].dns_public_ip }} {{ hostvars[host].ansible_hostname }}{{dns_domain}}\n{% endfor %}"
        line:   "{%for host in groups['openshift_nodes']%}{{ hostvars[host].dns_public_ip }} {{ hostvars[host].ansible_hostname }}{{dns_domain}}\n{% endfor %}"

    - name: "Run openshift installer"
      command: "ansible-playbook -e ansible_ssh_user=cloud-user -i {{ rhc_ose_inv_dest | default('/tmp') }}/inventory_{{ hostvars['localhost'].env_id }} /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml"
