---
# Provision OpenStack instances
- hosts: localhost
  pre_tasks:
  - include: roles/openstack-create/pre_tasks/pre_tasks.yml
  - include: roles/common/pre_tasks/pre_tasks.yml
  - include: roles/subscription-manager/pre_tasks/pre_tasks.yml
  roles:
    - role: common
    - role: openshift-common
    # Provision Master
    - role: openstack-create
      type: "master"
      image_name: "{{ openshift_openstack_image_name }}"
      security_groups: "{{ openshift_openstack_master_security_groups }}"
      key_name: "{{ openstack_key_name }}"
      flavor_name: "{{ openshift_openstack_flavor_name }}"
      register_host_group: "openshift_masters"
      node_count: "{{ openshift_master_count }}"
      disk_volume: "{{ openshift_storage_disk_volume }}"
      volume_size: "{{ openshift_openstack_master_storage_size }}"
    # Provision Nodes
    - role: openstack-create
      type: "node"
      image_name: "{{ openshift_openstack_image_name }}"
      security_groups: "{{ openshift_openstack_node_security_groups }}"
      key_name: "{{ openstack_key_name }}"
      flavor_name: "{{ openshift_openstack_flavor_name }}"
      register_host_group: "openshift_nodes"
      node_count: "{{ openshift_node_count }}"
      disk_volume: "{{ openshift_storage_disk_volume }}"
      volume_size: "{{ openshift_openstack_master_storage_size }}"

# Install and configure OpenShift
- hosts:
    - openshift_masters
    - openshift_nodes
  roles:
    - { role: subscription-manager, when: hostvars.localhost.rhsm_register, tags: 'subscription-manager', ansible_sudo: true }
    - { role: docker, tags: 'docker' }
    - { role: openshift-provision, tags: 'openshift-provision', ansible_sudo: true }
