---
# Provision OpenStack instances
- hosts: localhost
  pre_tasks:
  - include: roles/common/pre_tasks/pre_tasks.yml
  roles:
    - role: common
    - role: openshift-common
    # Provision Master
    - role: openstack-create
      type: "master"
      image_name: "{{ openshift_openstack_image_name }}"
      security_groups: "{{ openshift_openstack_master_security_groups }}"
      key_name: "{{ openstack_key_name }}"
      flavor_name: "{{ openshift_openstack_flavor_name }}"
      register_host_group: "openshift_masters"
      node_count: "{{ openshift_master_count }}"
      disk_volume: "{{ openshift_storage_disk_volume }}"
      volume_size: "{{ openshift_openstack_master_storage_size }}"
    # Provision Nodes
    - role: openstack-create
      type: "node"
      image_name: "{{ openshift_openstack_image_name }}"
      security_groups: "{{ openshift_openstack_node_security_groups }}"
      key_name: "{{ openstack_key_name }}"
      flavor_name: "{{ openshift_openstack_flavor_name }}"
      register_host_group: "openshift_nodes"
      node_count: "{{ openshift_node_count }}"
      disk_volume: "{{ openshift_storage_disk_volume }}"
      volume_size: "{{ openshift_openstack_master_storage_size }}"

    # Provision DNS

- include: playbooks/dns-provision.yaml

- hosts: all:!dns:!localhost
  remote_user: "cloud-user"
  become: true
  become_method: sudo
  become_user: root
  vars:
    ansible_ssh_user: cloud-user
    ansible_user: cloud-user
  roles:
    - role: hostnames

- hosts: all:!localhost
  remote_user: "cloud-user"
  become: true
  vars:
    ansible_ssh_user: cloud-user
    ansible_user: cloud-user
  roles:
    - { role: subscription-manager, repos: ["rhel-7-server-rpms", "rhel-7-server-ose-3.1-rpms", "rhel-7-server-extras-rpms"] }

- hosts: dns
  remote_user: "cloud-user"
  become: true
  vars:
    ansible_ssh_user: cloud-user
    ansible_user: cloud-user
  pre_tasks:
    - name: "Generate dns-server views"
      include: playbooks/dns_dual_view.yaml
      delegate_to: localhost

    - name: "Include the generated views"
      include_vars: /tmp/named_views.yaml
      delegate_to: localhost

    - name: "Include generated dns records"
      include: /tmp/records.yaml

  roles:
    - role: dns-server
    - role: dns


# Install and configure OpenShift
# - hosts:
#     - openshift_masters
#     - openshift_nodes
#   roles:
#     - role: subscription-manager
