---

  - name: "backup image streams"
    command: cp /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.1/image-streams/image-streams-rhel7.json /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.1/image-streams/image-streams-rhel7.json.orig
    when: target_registry is defined

  - name: "Configure ImageStreams"
    command: sed -i -e 's/registry.access.redhat.com/{{ target_registry }}/g' /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.1/image-streams/image-streams-rhel7.json
    when: target_registry is defined

  - name: "Check for existing registry"
    command: oc get dc docker-registry -n default
    register: registry_output
    ignore_errors: yes
    failed_when: "'FAILED' in registry_output.stderr"

  - name: "Checking for existing router"
    command: oc get dc router -n default
    register: router_output
    failed_when: "'FAILED' in router_output.stderr"

  - name: "Checking for existing ImageStreams"
    command: oc get is php -n openshift
    register: is_output
    failed_when: "'FAILED' in is_output.stderr"

  - name: "setup ose docker registry with images from registry other than redhat"
    shell: oadm registry --config=/etc/origin/master/admin.kubeconfig --credentials=/etc/origin/master/openshift-registry.kubeconfig --images='{{ target_registry }}/openshift3/ose-${component}:${version}' -n default
    when: target_registry is defined and registry_output.rc != 0

  - name: "setup ose docker registry"
    shell: oadm registry --config=/etc/origin/master/admin.kubeconfig --credentials=/etc/origin/master/openshift-registry.kubeconfig --images='registry.access.redhat.com/openshift3/ose-${component}:${version}' -n default
    when: target_registry is not defined and registry_output.rc != 0

  - name: "Create ImageStreams"
    command: oc create -f /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v1.1/image-streams/image-streams-rhel7.json -n openshift
    when: is_output.rc != 0

  - name: "Set insecured registry"
    command: oc annotate is --all -n openshift openshift.io/image.insecureRepository=true --overwrite
    when: target_registry is defined

  - name: "setup router"
    command: oadm router  --credentials='/etc/origin/master/openshift-router.kubeconfig' --service-account=router -n default
    when: router_output.rc != 0
