---
  
- name: Install Java
  yum:
    enablerepo: rhel-7-server-thirdparty-oracle-java-rpms
    name: java-1.8.0-oracle-devel
    state: present
  tags: java
  
- name: Determine Java Home Location
  shell: alternatives --list | grep jre_oracle | awk '{ print $3 }'
  register: java_root
  failed_when: java_root == ""
  tags: java


# TODO: Configure Custom Certificates 
 