---

  - name: "Checking for logging project"
    command: oc get project logging
    register: logging_project
    failed_when: "'FAILED' in logging_project.stderr"
    tags:
      - cleanup

  - name: "Create logging project"
    command: oadm new-project logging
    when: logging_project.rc != 0

  - name: "Changing projects"
    command: oc project logging
    tags:
      - cleanup

  - name: "Cleanup any previous logging infrastructure"
    command: oc delete all --selector logging-infra={{ item }} -n logging
    with_items:
      - kibana
      - fluentd
      - elasticsearch
    ignore_errors: yes
    tags:
      - cleanup

  - name: "Cleanup existing support infrastructure"
    command: oc delete all,sa,oauthclient --selector logging-infra=support -n logging
    ignore_errors: yes
    tags:
      - cleanup

  - name: "Cleanup existing secrets"
    command: oc delete secret logging-fluentd logging-elasticsearch logging-es-proxy logging-kibana logging-kibana-proxy logging-kibana-ops-proxy -n logging
    ignore_errors: yes
    register: clean_result
    failed_when: clean_result.rc == 1 and 'not found' not in clean_result.stderr
    tags:
      - cleanup

  - name: "Cleanup existing logging deployers"
    command: oc delete pods --all
    tags:
      - cleanup

  - name: "Creating logging deployer secret"
    command: oc secrets new logging-deployer kibana.crt=/etc/origin/master/ca.crt kibana.key=/etc/origin/master/ca.key ca.crt=/etc/origin/master/ca.crt ca.key=/etc/origin/master/ca.key
    register: secret_output
    failed_when: "secret_output.rc == 1 and 'exists' not in secret_output.stderr"

  - name: "Copy serviceAccount file"
    copy: dest=/tmp/logging-deployer-sa.yaml
          src={{role_path}}/files/logging-deployer-sa.yaml
          force=yes

  - name: "Create logging-deployer service account"
    shell: oc create -f  /tmp/logging-deployer-sa.yaml
    register: deployer_output
    failed_when: "deployer_output.rc == 1 and 'exists' not in deployer_output.stderr"

  - name: "Set permissions for logging-deployer service account"
    command: oc policy add-role-to-user edit system:serviceaccount:logging:logging-deployer
    register: permiss_output
    failed_when: "permiss_output.rc == 1 and 'exists' not in permiss_output.stderr"

  - name: "Set permissions for fluentd"
    command: oadm policy add-scc-to-user privileged system:serviceaccount:logging:aggregated-logging-fluentd
    register: fluentd_output
    failed_when: "fluentd_output.rc == 1 and 'exists' not in fluentd_output.stderr"

  - name: "Set additional permissions for fluentd"
    command: oadm policy add-cluster-role-to-user cluster-reader system:serviceaccount:logging:aggregated-logging-fluentd
    register: fluentd2_output
    failed_when: "fluentd2_output.rc == 1 and 'exists' not in fluentd2_output.stderr"

  - name: "Make sure to remove stale deployer template"
    command: oc delete template logging-deployer-template -n openshift
    register: delete_ouput
    failed_when: delete_ouput.rc == 1 and 'exists' not in delete_ouput.stderr

  - name: "Create deployer template"
    command: oc create -f /usr/share/openshift/examples/infrastructure-templates/enterprise/logging-deployer.yaml -n openshift
    register: template_output
    failed_when: "template_output.rc == 1 and 'exists' not in template_output.stderr"

  - name: "Clear out any previous pods"
    command: oc delete pods --all -n logging

  - name: "Process the deployer template with an registry other than registry.access.redhat.com"
    shell: oc process logging-deployer-template -n openshift -v KIBANA_HOSTNAME={{ kibana_hostname }},ES_CLUSTER_SIZE={{ es_cluster_size }},PUBLIC_MASTER_URL={{ master_url }},IMAGE_PREFIX={{ target_registry }}/  | oc create -f -
    when: target_registry is defined

  - name: "Process the default deployer template"
    shell: oc process logging-deployer-template -n openshift -v KIBANA_HOSTNAME={{ kibana_hostname }},ES_CLUSTER_SIZE={{ es_cluster_size }},PUBLIC_MASTER_URL={{ master_url }}  | oc create -f -
    when: target_registry is not defined

  - name: "Wait for image pull and deployer pod"
    action: shell oc get pods | grep logging-deployer.*Completed
    register: result
    until: result.rc == 0
    retries: 15
    delay: 10

  - name: "Process support template"
    shell: oc process logging-support-template | oc create -f -

  - name: "Set insecured registry"
    command: oc annotate is --all  openshift.io/image.insecureRepository=true --overwrite
    when: "target_registry is defined and insecure_registry == 'true'"

  - name: "Scale fluentd deployment config"
    command: oc scale dc/logging-fluentd --replicas={{ fluentd_replicas }}

  - name: "Wait for imagestreams to become available"
    action: shell oc get is | grep logging-fluentd
    register: result
    until: result.rc == 0
    failed_when: result.rc == 1 and 'not found' not in result.stderr
    retries: 15
    delay: 5

  - name: "Wait for replication controllers to become available"
    action: shell oc get rc | grep logging-fluentd-1
    register: result
    until: result.rc == 0
    failed_when: result.rc == 1 and 'not found' not in result.stderr
    retries: 15
    delay: 5

  - name: "Scale fluentd replication controller"
    command: oc scale rc/logging-fluentd-1 --replicas={{ fluentd_replicas }}

  - debug: msg="Logging components deployed. Note persistant volume for elasticsearch must be setup manually"
