#!/bin/bash

#
# Installs and Configures the CI/CD Server
#
# * Java JDK
# * Apache Maven
# * Jenkins CI Server
# * Sonatype Nexus Artifact Repository
#

set -e

#
# Constants
#

JAVA_VERSION=7u79
JAVA_VERSION_BUILD=b15
CICD_SETUP_DIR=/tmp/cicd-setup
CLOUD_ENV=0
NEXUS_VERSION=2.11.3-01
MAVEN_VERSION=3.3.3

SCRIPT_BASE_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

# Set Trap
trap clean_up EXIT

function clean_up() {

  if [ $? -eq 0 ]; then
	echo
	echo "====================================================="  
	echo "= CICD Server Provisioning Completed Successfully!  ="
	echo "====================================================="  
	echo
  else
  	echo
  	echo "====================================================="  
  	echo "= CICD Server Provisioning Failed!                  ="
  	echo "====================================================="  
  	echo
fi

  # Cleanup
  rm -rf ${CICD_SETUP_DIR}

}


#
# Function to install prerequisite packages
#

function install_prereqs() {
	yum install -y wget git
}

#
# Function to install the Java JDK
#

function install_java_jdk() {

  wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie" -O "${CICD_SETUP_DIR}/jdk-${JAVA_VERSION}-linux-x64.rpm" "http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION}-${JAVA_VERSION_BUILD}/jdk-${JAVA_VERSION}-linux-x64.rpm"
  rpm -Uvh ${CICD_SETUP_DIR}/jdk-${JAVA_VERSION}-linux-x64.rpm
  echo "export JAVA_HOME=/usr/java/latest" >> /etc/profile
  echo "export PATH=\$PATH:\$JAVA_HOME/bin" >> /etc/profile
  source /etc/profile
}


#
# Function to install additional Jenkins plugins
#
# Parameters:
# $1 - Name of the Jenkins plugin
# $2 - Version of the Jenkins plugin
#

function install_jenkins_plugin() {
	
	plugin_name=${1}
	plugin_version=${2}
	
	wget -O /var/lib/jenkins/plugins/${plugin_name}.hpi https://updates.jenkins-ci.org/download/plugins/${plugin_name}/${plugin_version}/${plugin_name}.hpi
	
}


#
# Function to install and configure the Jenkins CI server
#

function install_jenkins() {

  wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo
  rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key
  yum install -y jenkins
  
  cp -R ${SCRIPT_BASE_DIR}/cicd/jenkins/* /var/lib/jenkins
  
  # Install plugins
  mkdir -p /var/lib/jenkins/plugins
  
  install_jenkins_plugin 'github' '1.11.3'
  install_jenkins_plugin 'github-api' '1.68'
  install_jenkins_plugin 'git' '2.3.5'
  install_jenkins_plugin 'git-client' '1.17.1'
  install_jenkins_plugin 'credentials' '1.22'
  install_jenkins_plugin 'scm-api' '0.2'
  
  chown -R jenkins:jenkins /var/lib/jenkins
  
  iptables_jenkins='\-A INPUT \-p tcp \-m state \-\-state NEW \-m tcp \-\-dport 8080 \-j ACCEPT'
  [ $(grep -c '"$iptables_jenkins"' /etc/sysconfig/iptables) == 0 ] && \
  sed -i "/-A INPUT -j REJECT/i $iptables_jenkins" /etc/sysconfig/iptables
  
  service iptables restart
  
  chkconfig jenkins on
  service jenkins start

}

#
# Function to install Apache Maven
#

function install_maven() {

  wget -O ${CICD_SETUP_DIR}/apache-maven-${MAVEN_VERSION}-bin.tar.gz ftp://mirror.reverse.net/pub/apache/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
  tar xzf ${CICD_SETUP_DIR}/apache-maven-${MAVEN_VERSION}-bin.tar.gz -C /usr/local
  ln -s /usr/local/apache-maven-${MAVEN_VERSION} /usr/local/maven
  echo "export M2_HOME=/usr/local/maven" >> /etc/profile
  echo "export PATH=\$PATH:\$M2_HOME/bin" >> /etc/profile
  source /etc/profile

}

#
# Function to install the Nexus repository manager
#

function install_nexus() {
 
  wget -O ${CICD_SETUP_DIR}/nexus-${NEXUS_VERSION}-bundle.tar.gz https://sonatype-download.global.ssl.fastly.net/nexus/oss/nexus-${NEXUS_VERSION}-bundle.tar.gz
  tar xzf ${CICD_SETUP_DIR}/nexus-${NEXUS_VERSION}-bundle.tar.gz -C /usr/local 
  ln -s /usr/local/nexus-${NEXUS_VERSION} /usr/local/nexus
  useradd -m -d /usr/local/nexus -s /bin/bash nexus
  echo "export NEXUS_HOME=/usr/local/nexus" >> /etc/profile
  mkdir -p /var/run/nexus
  
  # Copy Configuration File
  mkdir -p /usr/local/sonatype-work/nexus/conf
  cp -f ${SCRIPT_BASE_DIR}/cicd/nexus/nexus.xml /usr/local/sonatype-work/nexus/conf/
  
  chown -R nexus:nexus /usr/local/nexus* /usr/local/sonatype-work /var/run/nexus
  cp /usr/local/nexus/bin/nexus /etc/init.d/
  chmod 755 /etc/init.d/nexus
  chown root /etc/init.d/nexus
  sed -i "s/NEXUS_HOME=\"..\"/NEXUS_HOME=\"\/usr\/local\/nexus\"/g" /etc/init.d/nexus
  sed -i "s/#PIDDIR=\".\"/PIDDIR=\"\/var\/run\/nexus\"/g" /etc/init.d/nexus
  sed -i "s/#RUN_AS_USER=/RUN_AS_USER=\"nexus\"/g" /etc/init.d/nexus
  
  iptables_nexus='\-A INPUT \-p tcp \-m state \-\-state NEW \-m tcp \-\-dport 8081 \-j ACCEPT'
  [ $(grep -c '"$iptables_nexus"' /etc/sysconfig/iptables) == 0 ] && \
  sed -i "/-A INPUT -j REJECT/i $iptables_nexus" /etc/sysconfig/iptables
   
  service iptables restart
  
  chkconfig --add nexus
  chkconfig --levels 345 nexus on
  service nexus start

}


echo "===================================="
echo "=   Installing CI/CD Environment   ="
echo "===================================="

# Create a scratch directory
mkdir -p ${CICD_SETUP_DIR}

echo
echo "--- Installing Prerequisite Software ---"
echo
install_prereqs

echo
echo "--- Installing Java ---"
echo
install_java_jdk

echo
echo "--- Installing Maven ---" 
echo
install_maven

echo
echo "--- Installing Jenkins ---" 
echo
install_jenkins

echo
echo "--- Installing Nexus ---" 
echo
install_nexus

