---
- name: Setting Registry Facts
  set_fact:
    template_registry_domain_name: "{{ registry_domain_name | default(default_domain_name) }}"
    certificate_path: "{{ default_certificate_path }}"
    certificate_subject: "{{ registry_certificate_subject | default(default_certificate_subject) }}"
    nginx_repo_url: "{{ registry_nginx_repo_url | default(default_nginx_repo_url) }}"
    auth_layer: "{{ registry_auth_layer | default(default_auth_layer) }}"

- name: Install Registry
  action: "{{ ansible_pkg_mgr }} name=docker-distribution state=latest"

- name: Enable & Start Registry
  service: name=docker-distribution enabled=yes state=started

- name: Install firewalld
  action: "{{ ansible_pkg_mgr }} name=firewalld state=latest"

#- name: Install firewall-cmd
#  yum: name=firewall-cmd state=latest

- name: Enable Firewalld
  service: name=firewalld enabled=yes state=started

- name: Open Firewall for Registry
  firewalld: port=5000/tcp permanent=yes state=enabled immediate=yes zone=public
  when: not auth_layer | bool

- name: Lay Down Registry Config
  template: src="{{role_path}}/templates/nginx.j2" dest="/etc/docker-distribution/registry/config.xml"
  notify: restart docker registry

- name: Add Auth Layer
  include: "{{role_path}}/tasks/auth_layer_nginx.yaml"
  when: registry_auth_layer | default(false) | bool
