- name: Creates directory
  file: path={{ certificate_path }} state=directory

- name: create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "{{ certificate_subject }}" -days 3650 -keyout {{ certificate_path }}/server.key -out {{ certificate_path }}/server.crt -extensions v3_ca creates={{ certificate_path }}/server.crt
